# Generated by Django 4.1.7 on 2023-02-27 18:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSettingToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pomodoro', models.IntegerField(default=25, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('small_rest', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('iterations_before_long_break', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('long_break', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PomodoroToUser',
        ),
        migrations.AlterField(
            model_name='currentpomodorosetting',
            name='pomodoro_setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pomodoro.pomodorosettingtouser'),
        ),
        migrations.DeleteModel(
            name='PomodoroSetting',
        ),
    ]
