# Generated by Django 4.1.7 on 2023-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0002_pomodorosettingtouser_delete_pomodorotouser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosettingtouser',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CurrentPomodoroSetting',
        ),
    ]
