# Generated by Django 4.1.7 on 2023-03-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_pomodorosettingtouser_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosettingtouser',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
